### ISSUE TITLE
Can I join in ?

### ISSUE THREAD

**Issue by SwenChan** [131/async-co#1]
Hi, I saw your project yesterday and I found that our idea so close.
I wrote a module like async but use generator like you, but some of my code is diff from yours and I use es6 and node6 and here is my code
```
function * eachLimit (coll, limit, iteratee) {
  const isArr = isArray(coll);
  const ent = isArr ? coll.entries() : makeEntries(coll);
  let results=  isArr ? [] : {};
  let workers = [];
  while(limit--) { // setup workers
    workers.push(nextJob());
  }
  yield workers;
  return results;

  function * nextJob () {
    const i = ent.next();
    if (i.done) return null;
    const [key, value] = i.value;
    results[key] = yield iteratee(value, key);
    yield nextJob();
  }
}
```

my main code is above.
And I'm going to translate 'auto' which is my favorite function in async.
Can I join in this project?

**Comment by 131** [comment]
We very welcome to join in !

Our code is exactly the same in its logic. The differences is that i need to use require('async-co/eachOfLimit') when i want to work with collections/dictionnaries.
I hope your can work with that

**Comment by SwenChan** [comment]
Thx for your reply!

**Comment by SwenChan** [comment]
Thx for your reply!
And how can I push my code here,give me a new branch or I just fork this repo and send PR to this ?
And I saw you use 'var' in your code , I think , probably, it's time to use 'let' and 'const'. I think may be  it's a good style in es6.
Or I also use 'var' :P ...

**Comment by 131** [comment]
please use const, and avoid let. (you can fork and submit a PR)
