### ISSUE TITLE
devtool Identifier 'global' has already been declared

### ISSUE THREAD

**Issue by chow-xiang** [131/async-co#3]
setImmediate.js
第三行：
`const global = (Function('return this'))();`

请把const改成var。
不然devtool开启时会报错。

报错信息如下：
`devtool Identifier 'global' has already been declared`

**Comment by idjem** [comment]
Thanks!

Has been done new version : async-co@1.7.0

**Comment by chow-xiang** [comment]
I,m sorry, I installed 1.7.0.
but also 'const'.

**Comment by idjem** [comment]
Yes but you will not have the error anymore ​.

the probleme was that node define alrady global so i change the name of our
variable to _global
